version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/2
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        links:
          - php
          - composer

    php:
        image: php:fpm
        volumes:
            - ./src:/2
        networks:
            - code-network
        ports:
            - "8082:8001"

    composer:
        restart: 'no'
        image: composer/composer:php7
        command: install
        volumes:
          - ./src:/2


networks:
    code-network:
        driver: bridge