version: '2'

services:
    web:
        image: nginx:latest
        environment:
            - ALLOW_OVERRIDE=true
        ports:
            - "8080:80"
        volumes:
            - ./:/app
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        links:
          - db
          - php
          - composer

    php:
        image: php:fpm
        volumes:
            - ./:/app
        networks:
            - code-network
        ports:
            - "8082:8001"

    composer:
        restart: 'no'
        image: composer/composer:php7
        command: install
        volumes:
          - ./:/app

    db:
        image: mariadb
        restart: always
        volumes:
          - ./mysql:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        ports:
          - "8889:3306"

networks:
    code-network:
        driver: bridge